[package]
name = "leptos-fetch-data"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.7.2", features = ["csr"] }
reqwest = "0.12.9"
serde = "1.0.216"
serde_json = "1.0.134"
tokio = "1.42.0"
